# Site settings
author: Erin
title: Front End 101
header-img: img/home-bg.png
email: ekstansbury@gmail.com
copyright_name: Erin
description: > # this means to ignore newlines until "baseurl:"
  lessons in git, ruby, JS, react
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  erinstansbury

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
